In [18]:
import numpy as np
import pandas as pd

# 為了讓每次亂數結果都一樣
np.random.seed(42)

In [19]:
# -------------------------
# 基本設定
# -------------------------

n_samples = 100 # 100位病人
n_genes = 100 # 100個基因

gene_names = [f"Gene{i}" for i in range(1, n_genes + 1)]

sample_names = [f"P{i}" for i in range(1, n_samples + 1)]

In [20]:
labels = (
    ["Virus"] * 25
    + ["Gram+"] * 25
    + ["Gram-"] * 25
    + ["Non"] * 25
)

In [21]:
expression = np.random.normal(
    loc=5,
    scale=1,
    size=(n_samples, n_genes)
)

In [ ]:
# 調整受感染下，基因表現的情況

virus_idx = np.array(labels) == "Virus"

expression[virus_idx, 0] += 3
expression[virus_idx, 1] += 3
expression[virus_idx, 2] += 3

gram_pos_idx = np.array(labels) == "Gram+"

expression[gram_pos_idx, 10] += 3
expression[gram_pos_idx, 11] += 3
expression[gram_pos_idx, 12] += 3

gram_neg_idx = np.array(labels) == "Gram-"

expression[gram_neg_idx, 20] += 3
expression[gram_neg_idx, 21] += 3
expression[gram_neg_idx, 22] += 3

In [23]:
expression_df = pd.DataFrame(
    expression,
    columns=gene_names,
    index=sample_names
)

expression_df["Label"] = labels

In [13]:
expression_df

,Gene1,Gene2,Gene3,Gene4,Gene5,Gene6,Gene7,Gene8,Gene9,Gene10,...,Gene92,Gene93,Gene94,Gene95,Gene96,Gene97,Gene98,Gene99,Gene100,Label
P1,8.496714,7.861736,8.647689,6.523030,4.765847,4.765863,6.579213,5.767435,4.530526,5.542560,...,5.968645,4.297947,4.672338,4.607892,3.536485,5.296120,5.261055,5.005113,4.765413,Virus
P2,6.584629,7.579355,7.657285,4.197723,4.838714,5.404051,6.886186,5.174578,5.257550,4.925554,...,5.856399,5.214094,3.754261,5.173181,5.385317,4.116143,5.153725,5.058209,3.857030,Virus
P3,8.357787,8.560785,9.083051,6.053802,3.622331,4.062175,5.515035,5.513786,5.515048,8.852731,...,4.506999,4.410635,5.849602,5.357015,4.307090,5.899600,5.307300,5.812862,5.629629,Virus
P4,7.171005,7.439819,8.747294,5.610370,4.979098,5.117327,6.277665,4.408429,5.547097,4.797807,...,5.491919,3.679767,6.831459,6.179440,4.530824,3.286865,6.353872,4.885460,6.237816,Virus
P5,6.405572,7.400625,8.005244,5.046981,4.549935,5.622850,3.932380,4.857621,5.120296,5.514439,...,6.479944,5.077368,4.138716,6.523124,5.538910,3.962754,4.809661,4.124382,3.617200,Virus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P96,4.732234,6.322703,5.175574,3.975249,6.848040,5.990711,4.878979,5.727171,4.596297,5.829149,...,4.688214,6.252346,6.136456,5.103118,4.548555,4.027172,4.962436,5.569759,4.675823,Non
P97,2.802499,6.268714,5.190223,4.620376,5.857158,6.524639,2.198088,5.434264,3.573351,5.499111,...,4.698202,7.530370,4.772107,4.769214,4.203013,5.123907,5.614961,6.203578,3.510716,Non
P98,4.754005,5.446704,5.587058,5.006549,5.542424,4.191036,6.557905,5.992628,3.655072,3.924897,...,5.335317,5.180305,4.043864,4.409182,6.245041,4.948491,5.375360,4.884812,3.816914,Non
P99,5.933810,5.503232,7.305637,3.984419,5.822573,3.688456,5.157347,5.976507,2.927865,4.795068,...,5.915824,4.636824,4.783581,4.863578,4.221691,4.556571,4.729730,6.612868,5.946618,Non
P100,5.934655,5.369926,3.882673,4.958509,5.970488,3.741735,5.636553,7.322609,6.061817,6.414029,...,5.191451,5.662169,3.501365,6.194214,6.301102,3.001655,4.294683,5.495766,5.644388,Non

In [ ]:
# 針對不同類型的感染 分別植入DGP

group_setting = {

    "Virus": (1,20),

    "Gram+": (21,40),

    "Gram-": (41,60),

    "Non": (61,80)

}

for label, (start, end) in group_setting.items():

    mask = expression_df["Label"] == label

    for i in range(start, end, 2):

        geneA = f"Gene{i}"
        geneB = f"Gene{i+1}"

        noise = np.random.normal(loc=2.0, scale=0.3, size=mask.sum())

        expression_df.loc[mask, geneA] = (
            expression_df.loc[mask, geneB] + noise
        )

In [25]:
expression_df

,Gene1,Gene2,Gene3,Gene4,Gene5,Gene6,Gene7,Gene8,Gene9,Gene10,...,Gene92,Gene93,Gene94,Gene95,Gene96,Gene97,Gene98,Gene99,Gene100,Label
P1,9.658187,7.861736,8.966346,6.523030,6.234294,4.765863,7.674316,5.767435,7.964254,5.542560,...,5.968645,4.297947,4.672338,4.607892,3.536485,5.296120,5.261055,5.005113,4.765413,Virus
P2,9.487705,7.579355,6.271372,4.197723,7.595112,5.404051,6.977527,5.174578,6.985776,4.925554,...,5.856399,5.214094,3.754261,5.173181,5.385317,4.116143,5.153725,5.058209,3.857030,Virus
P3,10.381570,8.560785,7.977246,6.053802,5.860871,4.062175,7.190291,5.513786,10.221951,8.852731,...,4.506999,4.410635,5.849602,5.357015,4.307090,5.899600,5.307300,5.812862,5.629629,Virus
P4,9.472944,7.439819,7.098984,5.610370,6.788576,5.117327,6.516104,4.408429,6.595745,4.797807,...,5.491919,3.679767,6.831459,6.179440,4.530824,3.286865,6.353872,4.885460,6.237816,Virus
P5,9.759779,7.400625,7.022041,5.046981,7.291514,5.622850,6.545683,4.857621,7.256974,5.514439,...,6.479944,5.077368,4.138716,6.523124,5.538910,3.962754,4.809661,4.124382,3.617200,Virus
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P96,4.732234,6.322703,5.175574,3.975249,6.848040,5.990711,4.878979,5.727171,4.596297,5.829149,...,4.688214,6.252346,6.136456,5.103118,4.548555,4.027172,4.962436,5.569759,4.675823,Non
P97,2.802499,6.268714,5.190223,4.620376,5.857158,6.524639,2.198088,5.434264,3.573351,5.499111,...,4.698202,7.530370,4.772107,4.769214,4.203013,5.123907,5.614961,6.203578,3.510716,Non
P98,4.754005,5.446704,5.587058,5.006549,5.542424,4.191036,6.557905,5.992628,3.655072,3.924897,...,5.335317,5.180305,4.043864,4.409182,6.245041,4.948491,5.375360,4.884812,3.816914,Non
P99,5.933810,5.503232,7.305637,3.984419,5.822573,3.688456,5.157347,5.976507,2.927865,4.795068,...,5.915824,4.636824,4.783581,4.863578,4.221691,4.556571,4.729730,6.612868,5.946618,Non
P100,5.934655,5.369926,3.882673,4.958509,5.970488,3.741735,5.636553,7.322609,6.061817,6.414029,...,5.191451,5.662169,3.501365,6.194214,6.301102,3.001655,4.294683,5.495766,5.644388,Non

In [78]:
expression_df.to_csv(r"C:\Users\USER\Desktop\資訊所實習\計畫\simulation_data_for_Biological_functions_of_the_DGPs\expression_df.csv", index=True)

In [62]:
pathway_db = {}

pathway_db["Virus_Core"] = [
    f"Gene{i}"
    for i in range(1,21)
]

pathway_db["GramPos_Core"] = [
    f"Gene{i}"
    for i in range(21,41)
]

pathway_db["GramNeg_Core"] = [
    f"Gene{i}"
    for i in range(41,61)
]

pathway_db["Non_Core"] = [
    f"Gene{i}"
    for i in range(61,81)
]

In [63]:
n_random = 6

for p in range(n_random):

    size = np.random.randint(12,21)

    genes = np.random.choice(
        gene_names,
        size=size,
        replace=False
    )

    pathway_db[f"Random_Pathway{p+1}"] = list(genes)

In [65]:
used = set()

for genes in pathway_db.values():

    used.update(genes)

unused = set(gene_names) - used

random_pathways = [
    p
    for p in pathway_db
    if "Random" in p
]

for gene in unused:

    p = np.random.choice(random_pathways)

    pathway_db[p].append(gene)

In [66]:
for gene in gene_names:

    extra = np.random.randint(0,3)

    available = []

    for pathway in random_pathways:

        if gene not in pathway_db[pathway]:

            available.append(pathway)

    if len(available)==0:
        continue

    selected = np.random.choice(
        available,
        size=min(extra,len(available)),
        replace=False
    )

    for pathway in selected:

        pathway_db[pathway].append(gene)

In [67]:
print(type(pathway_db))
print(len(pathway_db))

<class 'dict'>
10

In [68]:
print(pathway_db.keys())

dict_keys(['Virus_Core', 'GramPos_Core', 'GramNeg_Core', 'Non_Core', 'Random_Pathway1', 'Random_Pathway2', 'Random_Pathway3', 'Random_Pathway4', 'Random_Pathway5', 'Random_Pathway6'])

In [69]:
print(pathway_db["Virus_Core"])

['Gene1', 'Gene2', 'Gene3', 'Gene4', 'Gene5', 'Gene6', 'Gene7', 'Gene8', 'Gene9', 'Gene10', 'Gene11', 'Gene12', 'Gene13', 'Gene14', 'Gene15', 'Gene16', 'Gene17', 'Gene18', 'Gene19', 'Gene20']

In [70]:
for k, v in pathway_db.items():
    print(k, len(v))

Virus_Core 20
GramPos_Core 20
GramNeg_Core 20
Non_Core 20
Random_Pathway1 28
Random_Pathway2 35
Random_Pathway3 38
Random_Pathway4 30
Random_Pathway5 38
Random_Pathway6 26

In [71]:
used_genes = set()

for genes in pathway_db.values():
    used_genes.update(genes)

print("used genes:", len(used_genes))

used genes: 100

In [79]:
import json

with open(r"C:\Users\USER\Desktop\資訊所實習\計畫\simulation_data_for_Biological_functions_of_the_DGPs\pathway_db.json", "w") as f:
    json.dump(pathway_db, f, indent=4)

In [73]:
from collections import Counter

gene_count = Counter()

for genes in pathway_db.values():
    gene_count.update(genes)

counts = list(gene_count.values())

print("mean:", np.mean(counts))
print("min:", np.min(counts))
print("max:", np.max(counts))

mean: 2.75
min: 1
max: 5

In [80]:
gene_to_pathway = {}

for pathway, genes in pathway_db.items():
    for g in genes:
        gene_to_pathway.setdefault(g, []).append(pathway)

with open(r"C:\Users\USER\Desktop\資訊所實習\計畫\simulation_data_for_Biological_functions_of_the_DGPs\gene_to_pathway.json", "w") as f:
    json.dump(gene_to_pathway, f, indent=4)